language: python
python:
  - "3.6"
  - "nightly"
before_install:
  - pip install pytest
  - pip install coverage
  - pip install coveralls
install:
  - pip install pycrypto
script:
  - pytest
  - coverage run test_onekey.py
after_success:
  - coveralls