language: python
python:
  - "3.6"
  - "nightly"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install pycrypto
script:
  - pytest
after_success:
  - coveralls